name: excavator

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Look for new releases and update the manifests
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
